spring.application.name=biblioteca-api

spring.data.mongodb.uri=mongodb+srv://julianapenafielmelo221206_db_user:<db_password>@biblioteca-cluster.git0isr.mongodb.net/?appName=biblioteca-cluster

spring.data.mongodb.database=biblioteca_db

server.port=8080